"""added money to order_product

Revision ID: 0a6fa9cfa502
Revises: cb8e09274f14
Create Date: 2020-02-14 17:44:27.123177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6fa9cfa502'
down_revision = 'cb8e09274f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'money')
    # ### end Alembic commands ###
