"""added is_paid to stores_products

Revision ID: 4dba94b324b3
Revises: 556f9e59b055
Create Date: 2020-01-27 18:11:18.692711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dba94b324b3'
down_revision = '556f9e59b055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores_products', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores_products', 'is_paid')
    # ### end Alembic commands ###
