"""added tables stores_products, basket

Revision ID: 556f9e59b055
Revises: 83ecafa27056
Create Date: 2020-01-23 19:55:32.202424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556f9e59b055'
down_revision = '83ecafa27056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], )
    )
    op.create_table('stores_products',
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products_table.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores_table.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores_products')
    op.drop_table('basket')
    # ### end Alembic commands ###
