"""added title to stores

Revision ID: 83ecafa27056
Revises: 
Create Date: 2020-01-21 18:30:17.763718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ecafa27056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores_table', sa.Column('title', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_stores_table_title'), 'stores_table', ['title'], unique=True)
    op.drop_index('ix_stores_table_name', table_name='stores_table')
    op.drop_column('stores_table', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores_table', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_stores_table_name', 'stores_table', ['name'], unique=True)
    op.drop_index(op.f('ix_stores_table_title'), table_name='stores_table')
    op.drop_column('stores_table', 'title')
    # ### end Alembic commands ###
