"""added table order_product

Revision ID: ab2f7a2ae006
Revises: 99df8548352b
Create Date: 2020-02-05 17:53:44.702399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2f7a2ae006'
down_revision = '99df8548352b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('basket')
    op.alter_column('users_table', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_users_table_name', table_name='users_table')
    op.create_index(op.f('ix_users_table_name'), 'users_table', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_table_name'), table_name='users_table')
    op.create_index('ix_users_table_name', 'users_table', ['name'], unique=True)
    op.alter_column('users_table', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_table('basket',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products_table.id'], name='basket_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='basket_user_id_fkey')
    )
    op.drop_table('order_product')
    # ### end Alembic commands ###
